spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ #your database name
    username: #your database username
    password: #your database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: #give a AES-512 key
      expiration: #mention your jwt key expiration time in milliseconds
      refresh-token:
        expiration: #mention your refresh token key expiration time in milliseconds