spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: varavind2000@gmail.com
    password: hlar qfva izeh hmqz
    properties:
      mail:
#        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

application:
  security:
    jwt:
      secret-key: 70337336763979244226452948404D6351665468576D5A7134743777217A25432A462D4A614E645267556B586E3272357538782F413F4428472B4B6250655368
      expiration: 43200000 # a day(12 hours)
      refresh-token:
        expiration: 43200000 # a day (12 hours)